### ISSUE TITLE
leader.go crash (on ARM?)

### ISSUE THREAD

**Issue by miekg** [google/metallb#57]
**Is this a bug report or a feature request?**:

bug

**What happened**:

~~~
{"log":"/home/miek/g/src/go.universe.tf/metallb/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:175\n","stream":"stderr","time":"2017-12-14T21:51:19.205839696Z"}
{"log":"/home/miek/g/src/go.universe.tf/metallb/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:143\n","stream":"stderr","time":"2017-12-14T21:51:19.205899539Z"}
{"log":"/home/miek/g/src/go.universe.tf/metallb/arp-speaker/main.go:204\n","stream":"stderr","time":"2017-12-14T21:51:19.205958289Z"}
{"log":"/home/miek/upstream/go/src/runtime/asm_arm.s:971\n","stream":"stderr","time":"2017-12-14T21:51:19.206014955Z"}
{"log":"I1214 21:51:19.204827       1 leader.go:31] Lost leadership\n","stream":"stderr","time":"2017-12-14T21:51:19.206071725Z"}
{"log":"panic: runtime error: invalid memory address or nil pointer dereference [recovered]\n","stream":"stderr","time":"2017-12-14T21:51:19.207697751Z"}
{"log":"\u0009panic: runtime error: invalid memory address or nil pointer dereference\n","stream":"stderr","time":"2017-12-14T21:51:19.207999623Z"}
{"log":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8d48b0]\n","stream":"stderr","time":"2017-12-14T21:51:19.208521597Z"}
{"log":"\n","stream":"stderr","time":"2017-12-14T21:51:19.208590295Z"}
{"log":"goroutine 50 [running]:\n","stream":"stderr","time":"2017-12-14T21:51:19.20911581Z"}
{"log":"go.universe.tf/metallb/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)\n","stream":"stderr","time":"2017-12-14T21:51:19.209617368Z"}
{"log":"\u0009/home/miek/g/src/go.universe.tf/metallb/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0xfc\n","stream":"stderr","time":"2017-12-14T21:51:19.210387882Z"}
{"log":"panic(0x9a51c0, 0x10ec8e8)\n","stream":"stderr","time":"2017-12-14T21:51:19.210857877Z"}
{"log":"\u0009/home/miek/upstream/go/src/runtime/panic.go:491 +0x204\n","stream":"stderr","time":"2017-12-14T21:51:19.211375945Z"}
{"log":"go.universe.tf/metallb/vendor/k8s.io/client-go/tools/leaderelection/resourcelock.(*EndpointsLock).RecordEvent(0x11f78640, 0xa75c1d, 0xd)\n","stream":"stderr","time":"2017-12-14T21:51:19.211865211Z"}
{"log":"\u0009/home/miek/g/src/go.universe.tf/metallb/vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go:92 +0xfc\n","stream":"stderr","time":"2017-12-14T21:51:19.212389113Z"}
{"log":"go.universe.tf/metallb/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).acquire.func1()\n","stream":"stderr","time":"2017-12-14T21:51:19.21270937Z"}
{"log":"\u0009/home/miek/g/src/go.universe.tf/metallb/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:183 +0x98\n","stream":"stderr","time":"2017-12-14T21:51:19.213238271Z"}
{"log":"go.universe.tf/metallb/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0x123b5fb8)\n","stream":"stderr","time":"2017-12-14T21:51:19.213644205Z"}
{"log":"\u0009/home/miek/g/src/go.universe.tf/metallb/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x4c\n","stream":"stderr","time":"2017-12-14T21:51:19.214318938Z"}
{"log":"go.universe.tf/metallb/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x123b5fb8, 0x3b9aca00, 0x0, 0x33333333, 0x3ff33333, 0x12268001, 0x11f48000)\n","stream":"stderr","time":"2017-12-14T21:51:19.215461115Z"}
{"log":"\u0009/home/miek/g/src/go.universe.tf/metallb/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0x90\n","stream":"stderr","time":"2017-12-14T21:51:19.215834601Z"}
{"log":"go.universe.tf/metallb/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).acquire(0x12391000)\n","stream":"stderr","time":"2017-12-14T21:51:19.216152254Z"}
{"log":"\u0009/home/miek/g/src/go.universe.tf/metallb/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:175 +0xac\n","stream":"stderr","time":"2017-12-14T21:51:19.21667777Z"}
{"log":"go.universe.tf/metallb/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0x12391000)\n","stream":"stderr","time":"2017-12-14T21:51:19.216996829Z"}
{"log":"\u0009/home/miek/g/src/go.universe.tf/metallb/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:143 +0x40\n","stream":"stderr","time":"2017-12-14T21:51:19.217517918Z"}
{"log":"main.main.func1(0x12391000)\n","stream":"stderr","time":"2017-12-14T21:51:19.217822498Z"}
{"log":"\u0009/home/miek/g/src/go.universe.tf/metallb/arp-speaker/main.go:204 +0x1c\n","stream":"stderr","time":"2017-12-14T21:51:19.21833817Z"}
{"log":"created by main.main\n","stream":"stderr","time":"2017-12-14T21:51:19.218640251Z"}
{"log":"\u0009/home/miek/g/src/go.universe.tf/metallb/arp-speaker/main.go:204 +0x388\n","stream":"stderr","time":"2017-12-14T21:51:19.219161913Z"}
~~~

I'm not sure if I am holding it wrong or that is just doesn't work on ARM.

The
~~~
{"log":"I1214 21:51:19.204827       1 leader.go:31] Lost leadership\n","stream":"stderr","time":"2017-12-14T21:51:19.206071725Z"}
~~~
Indicates the callback is called just fine.

**Comment by miekg** [comment]
I going to continue *without* this code path, and setup a replicaset with replicas=1 for the time being

**Comment by miekg** [comment]
hmmm, I do pass in an `nil` EventRecorder
